---
- name: Edit kubeconfig
  lineinfile:
    path: /etc/ansible/config/k3s.yaml
    regexp: "^    server:"
    line: "    server: https://{{ apiserver_endpoint }}:6443"
- name: Check if environment variables already set (root)
  shell: grep -c "^# k3s" ~/.bashrc || true
  register: test_env_root
- name: Add environment variables if missing (root)
  lineinfile:
    path: ~/.bashrc
    insertafter: EOF
    line: "\n# k3s environment variables\nexport KUBECONFIG=/etc/ansible/config/k3s.yaml"
  when: test_env_root.stdout == "0"
- name: Install kubectl
  # Add checksum validation later
  shell: |
    curl -LO "https://dl.k8s.io/release/{{ k3s_version }}/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
- name: Install Traefik
  shell: |
    kubectl apply -f /etc/ansible/deployments/traefik-namespace.yml
    helm repo add traefik https://helm.traefik.io/traefik
    helm repo update
    helm install --namespace=traefik traefik traefik/traefik --values=/etc/ansible/traefik/values.yml
- name: Install middlewares for traefik
  shell: kubectl apply -f /etc/ansible/traefik/middleware/default-headers.yml
- name: Install apache2-utils
  shell: sudo apt-get install apache2-utils -y
- name: Install openshift (required for k8s module)
  shell: sudo pip install --upgrade --user openshift
- name: Add k8s module to ansible
  shell: ansible-galaxy collection install kubernetes.core