---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
  - role: prereq
  - role: download
  - role: raspberrypi

- hosts: master
  become: yes
  roles:
  - role: master

- hosts: node
  become: yes
  roles:
  - role: node

- hosts: ansible
  gather_facts: yes
  roles:
  - role: local